fix missing include of <time.h> in netw/tty_socket.c
tty_socket.c: In function ‘add_2p_tty’:
tty_socket.c:128:13: error: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
  128 |         if (time(NULL) - st.st_mtime > 3600) {
      |             ^~~~
tty_socket.c:16:1: note: ‘time’ is defined in header ‘<time.h>’; this is probably fixable by adding ‘#include <time.h>’
   15 | #include "internal.h"
  +++ |+#include <time.h>
   16 |

Signed-off-by: Ben Dooks <ben.dooks@codethink.co.uk>